trigger: none

pool:
  vmImage: "windows-latest"
  
variables:
  VsixName: "CodeVanguard.pandoc-staging.vsix" # $(VsixName)

stages:
- stage: DeployToStaging
  displayName: "Deploy to Staging"

  jobs:
  - job: Build
    steps: 
    - template: templates/VersionBuild.yml

    - template: templates/PreparePackage.yml
      parameters:
        vsixName: $(VsixName)
        extensionName: "PanDoc Tools - Staging"
        extensionId: "pandoc-staging"
        extensionVisibility: "private"

    - task: PublishBuildArtifacts@1
      displayName: Publish build artifacts
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)"
        ArtifactName: "drop"
        publishLocation: "Container"

  - deployment: Publish
    displayName: "Deploy staging"
    environment: "Staging"
    dependsOn: 'Build'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/PublishVsix.yml
            parameters:
              VsixName: $(VsixName)

- stage: TestExtension
  displayName: "Testing extension in staging"

  jobs:
    - job: RunTool
      displayName: "Running latest version of tool"
      steps:      
        - task: DownloadPanDoc@2
        
          displayName: "Downloading PanDoc"

        - task: RunPanDoc@2
          displayName: "Testing PanDoc"
          inputs:
            sourceFile: '$(System.DefaultWorkingDirectory)/Test/test.md'
            inputFormat: 'gfm'
            outputFormat: 'html5'
            destFile: '$(Build.ArtifactStagingDirectory)/test.html'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'