# This file is part of PanDoc for Azure Pipelines,
# Copyright (C) 2020-2022 Code Vanguard LLC

trigger: none

pool:
  vmImage: "windows-latest"
  
variables:
  VsixName: "CodeVanguard.code-vanguard-pandoc.vsix" # $(VsixName)

stages:
- stage: DeployToProduction
  displayName: "Deploy to Production"

  jobs:
  - job: Build
    steps:
      - template: templates/VersionBuild.yml    

      - template: templates/PreparePackage.yml
        parameters:
          vsixName: $(VsixName)
          extensionName: "PanDoc Tools"
          extensionId: "code-vanguard-pandoc-tasks"
          extensionVisibility: "public"

      - task: PublishBuildArtifacts@1
        displayName: Publish build artifacts
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "drop"
          publishLocation: "Container"
  
  - deployment: Publish
    displayName: "Deploy to production"
    environment: "Production"
    dependsOn: 'Build'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/PublishVsix.yml
            parameters:
              VsixName: $(VsixName)