# This file is part of PanDoc for Azure Pipelines,
# Copyright (C) 2020-2025 Code Vanguard LLC

trigger: none

pool:
  vmImage: 'windows-latest'

steps:
- task: DownloadPanDoc@2

- task: RunPanDoc@2
  inputs:
    sourceFiles: '$(System.DefaultWorkingDirectory)/README.md'
    inputFormat: 'gfm'
    outputFormat: 'html5'
    destFile: '$(Build.ArtifactStagingDirectory)/README.html'
    workingDirectory: $(System.DefaultWorkingDirectory)

- task: RunPanDoc@2
  inputs:
    sourceFiles: '$(System.DefaultWorkingDirectory)/README.md'
    inputFormat: 'gfm'
    outputFormat: 'docx'
    destFile: '$(Build.ArtifactStagingDirectory)/README.docx'
    workingDirectory: $(System.DefaultWorkingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
